### ISSUE TITLE
Build content script with :optimizations :none?

### ISSUE THREAD

**Issue by jacobmbr** [binaryage/chromex-sample#2]
With the current setup, recompiling my content script takes ~10s, most of it spent applying the `:whitespace` optimization to over 100 sources. 

On the other hand, passing `:optimizations :none` and a `:main` namespace to the compiler results in script tags with predictably wrong source paths being emitted.

Do you have a hint how to configure to build so I can develop without optimizations? 
Thank you. Your work on this project is greatly appreciated.

**Comment by darwin** [comment]
Unfortunately this is not easily possible. Content script has to be one javascript file because it is forbidden to load code dynamically into the content-script's javascript content (AFAIK).

I can see probably three options:
1) build it with `:optimizations :none` mode and use some custom script to concatenate all generated scripts basically emulating `:optimizations :whitespace` but faster
2) include all your 100+ scripts in [unpacked manifest.json](https://github.com/binaryage/chromex-sample/blob/ddbb285634f7654e1f71336a720420067f4eb4f5/resources/unpacked/manifest.json#L29) - this would be hard to maintain I guess
3) implement some kind of "engine" in content script, which would inject-script tags into the page's own javascript content and boot your content-script app there (one person on Slack did that successfully)

**Comment by darwin** [comment]
I can also imagine a solution via a special Chrome extension using chrome debugger protocol to eval code inside content-script's javascript context on-demand.

We would patch `goog.require` in content-script's content to delegate script loading to this extension and it would do the work for it. This would be available only for development of course.

I'm not going to do that personally, because I didn't hit the annoyance level you as you did. My content scripts are pretty small and my beefy iMac can deal with them pretty well :-)

**Comment by jacobmbr** [comment]
Thanks for getting back so quickly. I figured out a way using the [ClosureBuilder](https://developers.google.com/closure/library/docs/closurebuilder) Python script included in Google Closure, maybe this can save another stranded soul some hours:
- Compile with `:optimizations :none`.
- Use the `:notify-command` hook to call a shell script executing `closurebuilder.py` with `--namespace="chromex_sample.content_script" --root="resources/unpacked/compiled/content_script` and `-o script`. This builds a dependency tree from source and emits one big concatenated script with dependencies in the correct order.
- Pipe output to a file, overwriting the initial output from the `lein content` task.
- Include a new file `override.js` in the unpacked `manifest.json` that sets two variables:

```js
var CLOSURE_NO_DEPS = true;
var CLOSURE_UNCOMPILED_DEFINES = null;
```
---
See [here](https://medium.com/@wilkerlucio/setting-up-figwheel-for-chrome-extensions-content-scripts-f1631d8e782a) for another solution using `eval` injection as you alluded to. Not suitable for me b/c I need to stay in the isolated world to access Chrome APIs (and it feels slightly wrong).

**Comment by darwin** [comment]
I'm glad you found a solution. Yeah the linked blogpost about `eval` injection was done by the person from Slack channel.

I did read some more docs on [Content Scripts CSP](https://developer.chrome.com/extensions/contentSecurityPolicy#interactions) and they claim eval is not forbidden in content scripts. Maybe it would be just matter of patching `goog` to use some alternative method of fetching the sources and eval'ing them in the context of Content Script.
