### ISSUE TITLE
ClojureScript REPL supported?

### ISSUE THREAD

**Issue by krukow** [binaryage/chromex-sample#3]
I've just started experimenting with chromex-sample. I'm a beginning with the tooling, so forgive me if I'm asking too much of a newbie question. 

The project uses figwheel which is great. It is currently configured to not setup a ClojureScript REPL, and I’m wondering if there is a way to get the REPL working too or there is some reason why the REPL can’t be supported in the Chrome Extension environment?

Ideally what I'd want to achieve is 

* Using Emacs/CIDER jack-in or connect to ClojureScript repl 
* be able to use [Dirac](https://github.com/binaryage/dirac)

**Comment by darwin** [comment]
The REPL prompt got disabled here: https://github.com/binaryage/chromex-sample/blob/fc68fe87ce3d77b4e673a2516ff46884e9606c11/project.clj#L79. 

It was just due to technical limitation of `lein-cooper` which does not work well with interactive prompts (see the “devel” lein alias). When using `lein fig` and other non-cooper lein tasks directly in multiple terminal sessions it should be fine to enable the REPL option.

Please note that hot-reloading does not work for content-script code for [different reasons](#2).

**Comment by krukow** [comment]
Update unless you run 
```javascript
goog.require("figwheel.connect.build_background")
```
in `background.js` or `popup.js`, figwheel REPL is unable to connect with the app

accoding to @darwin this was changed here:

https://github.com/binaryage/chromex-sample/commit/a07c4fd412bf099cbc66c5a736e6f8932bdc71ff

and will be fixed very soon

**Comment by krukow** [comment]
👍
